---
title: "Class0 5.Rmd"
author: "Jontae Harris"
date: "2026-09-09"
output: 
  html_document:
    toc: true
    toc_float: true
    numbered_section: true
    code_download: true
    code_folding: show
    theme: simple
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Game 01: Subsetting Lists

```{r game01}
campus = jsonlite::fromJSON("https://isa401-find-your-seat.vercel.app/campus.json")
  
  
names(campus) # shows the named elements within a list (or vector)  or the cols in a data frame
fsb = campus$Farmer# saving the named farmer list in FSB
# equivalent campus [['Farmer]] by name or campus[[$]] by position
fsb$code


names(fsb[[8]]) # fsbfloors
fsb[[8]][[3]] # by position
fsb[[8]]$`2` # by name 

fsb[[8]]$'2'$sections
sec_floor = fsb[[8]]$`2`

sec_floor_rooms = sec_floor[[3]]
sec_floor_rooms[6, 2] # by position 
sec_floor_rooms[6, 'isa_sections'] # by name
```



## Reading the Exce File

```{r occupations}
occupation = readxl::read_excel(
  path = "../data/occupation.xlsx", 
  sheet = 5, # sheet = "Table 1.4" 
  skip = 1
)
# - when you subset in R drops these specific things
# given that they are three, i put them in a vector 
# notice the "," after the parantheses
# nothing after the comma which means all columns
# instead of that space --> 1:7 
occupation = occupation[-c(32, 33, 34), ]

# alternatively 
occupation = occupation[1:31, ]
```

## Read JSON Data

```{r read_JSON}
json_url = "https://data.cincinnati-oh.gov/resource/rvmt-pkmq.json?$limit=100"

crashes_json = jsonlite::fromJSON(json_url)
dplyr::glimpse(
  crashes_json[, c("crashdate", "dayofweek",
                   "crashseverity", "age")])
```


## Game 02 
```{r}

```

```{r}
logins = readr::read_csv("https://isa401-import-heist.vercel.app/api/stage1")

log = jsonlite::fromJSON("https://isa401-import-heist.vercel.app/api/stage2?key=ACCOUNT")
events_df = log$events # 6 files were dowloaded 
jsonlite::fromJSON("https://isa401-import-heist.vercel.app/api/finish?code=NUMBER")

```








