---
title: "class 07"
author: "Jontae Harris"
date: "2026-09-16"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
con = DBI::dbConnect(RSQLite::SQLite(), "../data/scout.db")
postings = DBI::dbReadTable(con, "scout_postings") |> tibble::as_tibble()
DBI::dbDisconnect(con)
jobs = postings |>
  dplyr::select(company, title, location_state, remote, category, posted_at, last_seen_at) |>
  dplyr::mutate(dplyr::across(dplyr::ends_with("_at"), as.Date),
                days_open = as.numeric(last_seen_at - posted_at))
    



jobs
# q1 -- which cat is remote friendly 
# to answer that, the logic would be as follows"
# - Find the number of jobs per category
# - Normalize the number or emote jobs by dividing by the total jobs 



jobs |> 
  # I want to move from unit of analysis being a job posting to a category 
  dplyr:: group_by(category)|> 
  dplyr:: summarise(
    postings = dplyr::n(),
    remote_share = mean(remote)
    #remind Dr. Fadel to show how to compute remote_share diff in next class
    )

```

