---
title: "class 07"
author: "Jontae Harris"
date: "2026-09-16"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
con = DBI::dbConnect(RSQLite::SQLite(), "../data/scout.db")
postings = DBI::dbReadTable(con, "scout_postings") |> tibble::as_tibble()
DBI::dbDisconnect(con)


jobs = postings |>
  dplyr::select(company, title, location_state, remote, category, posted_at, last_seen_at) |>
  dplyr::mutate(dplyr::across(dplyr::ends_with("_at"), as.Date),
                days_open = as.numeric(last_seen_at - posted_at))
  


jobs
# q1 -- which cat is remote friendly 
# to answer that, the logic would be as follows"
# - Find the number of jobs per category
# - Normalize the number or emote jobs by dividing by the total jobs 



jobs |> 
  # I want to move from unit of analysis being a job posting to a category 
  dplyr:: group_by(category)|> 
  dplyr:: summarise(
    postings = dplyr::n(),
    remote_share = mean(remote)
    )

# Among full-time postings, which states have the highest remote share?
# Based on the vote in class, we will dviate from the answer in the slide 
# by showing the combination of category and state -- this will still give you the answer you want

jobs |> 
  dplyr::group_by(category, location_state) |>
  dplyr::summarise(
    posting = dplyr::n(), 
    remote_share = mean(remote)|> round(digits = 2)
  ) |>
    dplyr::arrange(dplyr::desc(remote_share)) |>
    na.omit() # to drop the location _state ==NA and any other rows that contain NA
  
  # Notes Logic 

  jobs |> 
  dplyr::filter(category== 'fulltime')|>
  dplyr::group_by(category, location_state) |>
  dplyr::summarise(
    posting = dplyr::n(), 
    remote_share = mean(remote)|> round(digits = 2)
  ) |>
    dplyr::arrange(dplyr::desc(remote_share)) |>
    na.omit() 
```

## Airbnb

```{r}
con = DBI::dbConnect(RSQLite::SQLite(), "../data/midwest_airbnb.db")
listings = DBI::dbReadTable(con, "listings") |>
  tibble::as_tibble()
DBI::dbDisconnect(con)
dplyr::glimpse(listings)

#1. How many listings per city?
## If the answer is purely based on last class, I can group by city and then count the number of listing in each city

listings |> dplyr::group_by(city) |> dplyr::summarise(count = dplyr::n())
# alternatively, the short cut for the code above
listings |> dplyr::count(city) # count does group by and then n()

#the other option is to simply count the number of times each city occurred in the col city 
table(listings$city) # returns a named vector above vs we get a data.frame/tibble

# 2. For entire homes (room_type == "Entire home/apt") that sleep four or more, what is the median price in each city?
listings |> 
  dplyr::filter(
    room_type == "Entire home/apt" & accommodates >= 4
  ) |>
  dplyr::group_by(city) |> 
  dplyr:: summarise(
    median_price = median(price)
  )
  

```



